### ISSUE TITLE
Commit Messages

### ISSUE THREAD

**Issue by SNikhill** [jocke1234/google-homepage#1]
I was just checking out your progress till now and I was greeted by a commit message that said you were still trying to work up the sign up button. Although, it doesn't concern me but, I must say that you need to follow the recommended guidelines and only commit to a remote repository if you have completed the part you were working on (so as to avoid words like: "still trying").

**Please note** that, I did not mean to offend you in anyway. I am just trying to share what I have learnt (and still am). [This](https://chris.beams.io/posts/git-commit/) might help you :)

Thanks
Nikhil Seth

**Comment by jocke1234** [comment]
Ah okay thanks for the tip mate! Im new to this whole github and i remember reading somewhere that i should commit as often as possible but thats a valid point that i should only do that after everything works.. :)
